version: '3.8'
services:
  unbound_export:
    build: .
    container_name: unbound_export
    ports:
      - "${EXPORT_PORT}:9798"
    environment:
      OPNSENSE_API_KEY: ${OPNSENSE_API_KEY}
      OPNSENSE_API_SECRET: ${OPNSENSE_API_SECRET}
      OPNSENSE_HOST: ${OPNSENSE_HOST}
      EXPORT_PORT: ${EXPORT_PORT}
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    restart: unless-stopped
