services:
  unbound_export:
    build: .
    container_name: unbound_export
    ports:
      - "${EXPORTER_PORT}:9797"
      - "${FLASK_PORT}:9798"
    environment:
      OPNSENSE_API_KEY: ${OPNSENSE_API_KEY}
      OPNSENSE_API_SECRET: ${OPNSENSE_API_SECRET}
      OPNSENSE_HOST: ${OPNSENSE_HOST}
      EXPORTER_PORT: ${EXPORTER_PORT}
      SCRAPE_INTERVAL: ${SCRAPE_INTERVAL}
      TZ: ${TZ}
    restart: unless-stopped

