services:
  unbound_export:
    build: .
    container_name: unbound_export
    volumes:
      - /etc/localtime:/etc/localtime:ro  # Sync time with host
    ports:
      - "${EXPORTER_PORT}:9797"
      - "${FLASK_PORT}:9798"
    environment:
      OPNSENSE_API_KEY: ${OPNSENSE_API_KEY}
      OPNSENSE_API_SECRET: ${OPNSENSE_API_SECRET}
      OPNSENSE_HOST: ${OPNSENSE_HOST}
      EXPORTER_PORT: ${EXPORTER_PORT}
      FLASK_PORT: ${FLASK_PORT}  
      SCRAPE_INTERVAL: ${SCRAPE_INTERVAL}
      TZ: America/Chicago
    restart: unless-stopped

